spring:
  application:
    name: interviewprep
  datasource:
    url: jdbc:h2:mem:employeeDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: '*'